apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: agaspar
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-01-20T13:30:21Z"
  generation: 1
  labels:
    app: deno-webserver
    app.kubernetes.io/managed-by: Helm
  name: agaspardeno-webserver
  namespace: default
  resourceVersion: "146058"
  uid: be248103-ff1a-4648-8f63-39c35ad7df81
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deno-webserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deno-webserver
    spec:
      containers:
      - image: codebuds/deno-webserver:1.3.1
        imagePullPolicy: IfNotPresent
        name: deno-webserver
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /probe?probeType=readiness
            port: http
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /srv/app/pvc
          name: agasparlogs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: agaspardefault-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: agasparlogs
        persistentVolumeClaim:
          claimName: agasparlogs
status:
  conditions:
  - lastTransitionTime: "2023-01-20T13:30:21Z"
    lastUpdateTime: "2023-01-20T13:30:21Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2023-01-20T13:30:21Z"
    lastUpdateTime: "2023-01-20T13:30:21Z"
    message: ReplicaSet "agaspardeno-webserver-78df7b9b77" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 3
  unavailableReplicas: 3
  updatedReplicas: 3
